---
# =============================================================================
# Created By  : Simon Schaefer
# Description : YAML - Image domain with autoencoder for MNIST dataset. 
# =============================================================================

# Training and validation datasets. 
datasets_train: 
  - "MNIST_train"

datasets_valid: 
  - "MNIST_valid"

# Model (model name from model dictionary).  
model: "AEMNIST_1D"

# Training parameters. 
# - num_epochs:     Number of training iteration through training dataset.
# - batch_size:     Size of samples which are optimized in parallel. 
# - learning_rate:  Model parameters adaption while learning. 
# - lr_decay_gamma: Factor to decrease learning rate (adaptive learning rate). 
# - lr_decay_steps: Number of training steps with same learning rate. 
# - weight_decay:   L2 parameters penalization. 
num_epochs:  100
batch_size:  128
learning_rate: 0.01
lr_decay_gamma: 0.1
lr_decay_steps: 40
weight_decay: 0.00001

# Autoencoder parameters. 
# - subsize:  To maintain a certain input image size for the model 
#             not the whole image is inputted but a random subsample of quadratic
#             size, with length subsize. Has to be an even numer (i.e. "evenly" 
#             dividable by scale factor).
# - scale_guidance: Scale guidance determines the scale of the resulting LR image 
#             w.r.t. the HR image (i.e. 2 = two times smaller). 
scale_guidance: 4
subsize       : 28

...